Ilya mazepa
DenisBorisov-lab/invest-dashboard pull request #4
Opened 2024-04-11 22:39 UTC by Tyhyqo

2024-04-11 22:55 UTC, DenisBorisov-lab reviewed
есть небольшие замечания

2024-04-11 22:55 UTC, DenisBorisov-lab commented on backend/model/db_session.py
> +        f'postgresql://185.127.225.251:karasik_sanichka2003@'
Молодец что добавил url базы данных, развернутой на сервере

2024-04-11 22:55 UTC, DenisBorisov-lab commented on backend/model/profile.py
> +    profile_id = Column(VARCHAR(200), primary_key=True, nullable=False)
profile_id должен иметь тип Integer, а не varchar

2024-04-11 23:16 UTC, DenisBorisov-lab requested changes

2024-04-11 23:16 UTC, DenisBorisov-lab commented on backend/model/profile.py
> +    __tablename__ = 'Profile'
Сделать название таблицы в нижнем регистре

2024-04-11 23:16 UTC, DenisBorisov-lab commented on backend/model/profile.py
> +    bitcoin = Column(DOUBLE, default=0)
Изменить тип полей на Decimal

2024-04-11 23:16 UTC, DenisBorisov-lab commented on backend/model/profile.py
> +    user = orm.relationship('User', back_populates='profile')
user сделать с маленькой буквы

2024-04-11 23:44 UTC, DenisBorisov-lab requested changes

2024-04-11 23:44 UTC, DenisBorisov-lab commented on backend/model/profile.py
> +    bitcoin = Column(DOUBLE)
Заменить Double на Decimal и добавить defaultValue

2024-04-11 23:44 UTC, DenisBorisov-lab commented on backend/model/users.py
> +    __tablename__ = 'User'
user в нижнем регистре

2024-04-11 23:44 UTC, DenisBorisov-lab commented on backend/model/users.py
> +    password = Column(VARCHAR, nullable=False)
указать размерность varchar, размерность смотрите в Miro

2024-04-11 23:44 UTC, DenisBorisov-lab commented on backend/model/users.py
> +    profile = orm.relationship('Profile', back_populates='user')
profile с маленькой буквы

2024-04-11 23:44 UTC, DenisBorisov-lab commented on backend/utils/crud_profile.py
> +                bitcoin=0):
Убираем кучу параметров, вместо них делаем объект класса BaseModel
https://fastapi.tiangolo.com/tutorial/sql-databases/#use-pydantics-orm_mode

2024-04-11 23:44 UTC, DenisBorisov-lab commented on backend/utils/crud_profile.py
> +        return f'{username} already has a profile'
Убираем try except и вместо него вставляем проверку на то, есть ли пользователь в базе данных

2024-04-11 23:44 UTC, DenisBorisov-lab commented on backend/utils/crud_profile.py
> +    return 'Success'
возвращаем сохраненный профайл, Session не должна создаваться в функции, смотрим ссылку выше и передаем сессию в качестве аргумента

2024-04-11 23:44 UTC, DenisBorisov-lab commented on backend/utils/crud_profile.py
> +    return 'Success'
1. разбить на две функции, удалить по profile_id и по username
2. Вместо .first написать one_or_none, проверять на none вместо обработки ошибки
3. Про сессию аналогично
4. Возвращать bool значение

2024-04-11 23:44 UTC, DenisBorisov-lab commented on backend/utils/crud_profile.py
> +    return 'Success'
Переписать полностью согласно вышеупомянутым комментариям

2024-04-12 10:42 UTC, Tyhyqo commented on backend/model/profile.py
> +    user = orm.relationship('User', back_populates='profile')
Тут должно быть с большой, он отсылается на имя класса

2024-04-12 10:44 UTC, Tyhyqo commented on backend/model/users.py
> +    profile = orm.relationship('Profile', back_populates='user')
Аналогично, это ссылка на название класса

2024-04-13 10:57 UTC, merged